repos:
# -   repo: https://github.com/ambv/black
#     rev: stable
#     hooks:
#     - id: black
#       language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: check-added-large-files
#     - id: flake8
-   repo: https://git.ag.ny.gov/research/pre-commit
    rev: v0.7
    hooks:
    - id: pip-freeze-update
